language: sh
sudo: required

env:
  matrix:
    - GHCVER=7.4.2
    - GHCVER=7.6.3
    - GHCVER=7.8.4
    - GHCVER=7.10.1 CABAL_FLAGS="-frun-integrated-test"
  global:
    - secure: "XP4CiTXFiE9m0cYYDfP8KwFUoxE95yBpwxfKMSxX9ue5mjzUjwfO+NVAAEeZszdgCtVnZUvfrWo0Yy626hlMUhW7vrvdqTRVZyYwRL1wbDeSVmde45QW7UTuFmkhvMV1lbhBEuyik1OSaX+hfJ1nAs3s2qoSuCFZEPh/k/sA3M4=" # HALCYON_AWS_ACCESS_KEY_ID
    - secure: "Zflb7SKA4M4JuOnYxBw9Chju2/zXXqfuOm75id9mplc8cJ/hM2YitDLidTrI72zZ8pqffvAIBz4pq3Zz/Dnu2qUfbAFe9uXWeBOYVZ+NDdMqitgyjAZ/F8UDcwFE8Q2/P8qMVXKyoKHWXUDdtBj+kr/HYfArxz8jTQB+gWV6R2k=" # HALCYON_AWS_SECRET_ACCESS_KEY

    # OAUTH_CONSUMER_KEY
    - secure: "U3hh6wJf87tdZmwLtPyMQ0ci39ouKvTm/JCi0CCz2jaPvWZR+4Tt7aYV5WYqzjSmgfBOqKpXTpwFBcvvWRty8rI1b8OtrlljC1zUcgf/hsz3hfPtv+GKW/ldYnqg7znyeAdxWEF1a4JszKgOJaGMdX7zSpFewgwEq7T4jAlebLA="
    # OAUTH_CONSUMER_SECRET
    - secure: "I4BGd16zNQE3WjnwgdT7OM5sIIMtT9DMFPNdnWJPcgYndDovnFAUDoTomaGo0Wue4h64vGWl26f2Nm04i2upJXxkzFFtU5Az6cwUjzkOve1yqrkkyPFTXC8MLQYX3Zz8scQ8h1IJCn0Luu5HsHsool6IFZpiUovLZbDXmY44yH4="
    # OAUTH_ACCESS_TOKEN
    - secure: "dW2pYRplxJ7HmJEo3lMgLlzfdOylBvWiV4PJt1j4GMDPJBOu3RM0h3zNkkxDoS9D0wWRkBEH0iN2Bh08v2z7sJtF3f/kgLvPlOy5mNSYcozwMdHJRlJEcXaGULHbZ4p79lVIOdTAhY2WU2QdP7PEv0BiqqVcysnfK0TGkTa+KEc="
    # OAUTH_ACCESS_SECRET
    - secure: "I5hzi7sONDn8KJAhmkroHsGNJ2zUxYq2iGamTV9lgMUDH0bwpMx+guzfZr+fGesdlUphM0t+ZCh9YH8BoVJsjZ/db9u/lotg78DKp1QwhrWnISqWj6TIfXrSLPkBwY+xFtxl6Ihsjyl+ileiK5sb0C9mC+zXidgBqEM73miAokY="

matrix:
  allow_failures:
    - env: GHCVER=7.4.2
    - env: GHCVER=7.6.3

before_install:
  - eval "$( curl -sL https://github.com/mietek/halcyon/raw/master/setup.sh )"
  - export HALCYON_GHC_VERSION=$GHCVER HALCYON_CABAL_VERSION=1.22.4.0
  - export HALCYON_S3_BUCKET=himura-halcyon

install:
  - HALCYON_SANDBOX_EXTRA_APPS="hpc-coveralls happy" HALCYON_SANDBOX_EXTRA_CONFIGURE_FLAGS="--enable-tests --only-dependencies $CABAL_FLAGS" halcyon build
  - ln -s /app/sandbox/cabal.sandbox.config .

script:
  - cabal configure --enable-tests --enable-library-coverage $CABAL_FLAGS
  - travis_wait run-cabal-test --cabal-name=cabal --show-details=always

after_script:
  - hpc-coveralls --exclude-dir=tests tests
